-- 达梦补充脚本：表注释 + 字段注释 + 索引
-- 说明：
-- 1. 本脚本用于“表已建好，但注释/索引缺失”的补充场景。
-- 2. 若索引已存在，CREATE INDEX 会报错；正式执行前可先人工确认或先删后建。

/* =========================================================
   1) 表与字段注释
   ========================================================= */

-- ODS_DWEQ_DM_AREA_D
COMMENT ON TABLE ODS_DWEQ_DM_AREA_D IS 'area表';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.parent_id IS '父级区域ID';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.name IS '区域名称';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.type IS '区域类型';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.path_ids IS '路径ID串';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.path_names IS '路径名称串';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.deleted IS '是否删除 0否1是';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.sort IS '排序号';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.creator IS '创建人';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.updator IS '更新人';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.deletor IS '删除人';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.updated_on IS '更新时间';
COMMENT ON COLUMN ODS_DWEQ_DM_AREA_D.deleted_on IS '删除时间';

-- ODS_DWEQ_DM_ORG_D
COMMENT ON TABLE ODS_DWEQ_DM_ORG_D IS 'org表';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.parent_id IS '父级机构ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.name IS '机构名称';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.type IS '机构类型';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.path_ids IS '路径ID串';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.path_names IS '路径名称串';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.sort IS '排序号';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.creator IS '创建人';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.updator IS '更新人';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.deletor IS '删除人';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.updated_on IS '更新时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ORG_D.deleted_on IS '删除时间';

-- ODS_DWEQ_DM_DEVICE_D
COMMENT ON TABLE ODS_DWEQ_DM_DEVICE_D IS 'device表';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.device_type IS '设备类别';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.name IS '设备名称';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.area_id IS '所属区域ID';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.iot_code IS '物联编码';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.model IS '设备型号';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.manufacturer IS '生产厂家';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.factory_date IS '出厂日期';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.run_date IS '投运日期';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.asset_status IS '资产状态';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.org_id IS '所属机构ID';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.remark IS '备注';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.online_status IS '在线状态';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.last_report_time IS '最近上报时间';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.last_offline_time IS '最近离线时间';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.creator IS '创建人';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.updator IS '更新人';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.deletor IS '删除人';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.updated_on IS '更新时间';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_D.deleted_on IS '删除时间';

-- ODS_DWEQ_DM_MONITOR_D
COMMENT ON TABLE ODS_DWEQ_DM_MONITOR_D IS 'monitor表';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.name IS '监测对象名称';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.area_id IS '区域ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.area_name IS '区域全路径名称，使用斜杠分隔';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.elevator_count IS '电梯数量';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.shaft_type IS '竖井类型';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.monitor_status IS '监测状态';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.build_date IS '建成日期';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.owner_company IS '产权单位';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.remark IS '备注';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.creator IS '创建人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.updator IS '更新人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.deletor IS '删除人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.updated_on IS '更新时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_D.deleted_on IS '删除时间';

-- ODS_DWEQ_DM_SHAFT_FLOOR_D
COMMENT ON TABLE ODS_DWEQ_DM_SHAFT_FLOOR_D IS 'ODS_DWEQ_DM_SHAFT_FLOOR_D表';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.monitor_id IS '监测对象ID';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.area_id IS '区域ID';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.name IS '楼层名称';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.start_point IS '开始点位';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.end_point IS '结束点位';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.sort IS '排序号';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.creator IS '创建人';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.updator IS '更新人';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.deletor IS '删除人';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.updated_on IS '更新时间';
COMMENT ON COLUMN ODS_DWEQ_DM_SHAFT_FLOOR_D.deleted_on IS '删除时间';

-- ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D
COMMENT ON TABLE ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D IS 'ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D表';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.monitor_id IS '监测对象ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.bind_status IS '绑定状态';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.bind_time IS '绑定时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.unbind_time IS '解绑时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.creator IS '创建人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.updator IS '更新人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.deletor IS '删除人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.updated_on IS '更新时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D.deleted_on IS '删除时间';

-- ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D
COMMENT ON TABLE ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D IS 'ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D表';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.monitor_id IS '监测对象ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.shaft_floor_id IS '楼层ID';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.partition_id IS '分区标识，对应消息PartitionId';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.partition_code IS '分区编码';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.partition_name IS '分区名称';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.data_reference IS 'MQ数据引用';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.device_token IS '设备编码片段';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.partition_no IS '分区序号';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.bind_status IS '绑定状态';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.creator IS '创建人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.updator IS '更新人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.deletor IS '删除人';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.updated_on IS '更新时间';
COMMENT ON COLUMN ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D.deleted_on IS '删除时间';

-- ODS_DWEQ_DM_ALARM_D
COMMENT ON TABLE ODS_DWEQ_DM_ALARM_D IS 'alarm表';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.alarm_code IS '告警单号';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.alarm_type IS '告警类型';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.source_type IS '来源类型';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.monitor_id IS '监测对象ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.shaft_floor_id IS '楼层ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.partition_code IS '分区编码';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.partition_name IS '分区名称';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.data_reference IS 'MQ数据引用';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.device_token IS '设备编码片段';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.partition_no IS '分区序号';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.source_format IS '数据来源格式';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.merge_key IS '待确认合并占位键';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.status IS '告警状态码 0待确认1已确认2持续观察3误报4关闭5自动恢复';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.first_alarm_time IS '首次告警时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.last_alarm_time IS '最近告警时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.merge_count IS '累计触发次数';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.event_count IS '已记录事件次数';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.alarm_level IS '告警等级';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.title IS '告警标题';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.content IS '告警内容';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.handler IS '处理人ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.handle_time IS '处理时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.handle_remark IS '处理备注';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.push_status IS '推送状态 0未推送1已推送';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_D.updated_on IS '更新时间';

-- ODS_DWEQ_DM_ALARM_RAW_D
COMMENT ON TABLE ODS_DWEQ_DM_ALARM_RAW_D IS '上游告警原始数据表';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.iot_code IS '设备唯一标识，取topic设备段';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.topic IS '原始topic';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.partition_id IS '分区标识';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.alarm_status IS '上游告警状态 0/1';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.fault_status IS '上游故障状态 0/1';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.ied_full_path IS '完整路径';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.data_reference IS '消息数据引用';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.collect_time IS '采集时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.payload_json IS '原始消息项JSON';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RAW_D.created_on IS '创建时间';

-- ODS_DWEQ_DM_ALARM_RULE_D
COMMENT ON TABLE ODS_DWEQ_DM_ALARM_RULE_D IS '告警规则表';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.rule_name IS '规则名称';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.biz_type IS '业务类型 MONITOR/DEVICE';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.alarm_type IS '告警类型';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.scope_type IS '作用范围，当前固定为GLOBAL';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.scope_id IS '作用对象ID，当前固定为NULL';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.level IS '告警等级';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.threshold_value IS '主阈值';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.threshold_value2 IS '副阈值';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.duration_seconds IS '持续时长秒数';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.enabled IS '是否启用';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.remark IS '备注';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_ALARM_RULE_D.updated_on IS '更新时间';

-- ODS_DWEQ_DM_EVENT_D
COMMENT ON TABLE ODS_DWEQ_DM_EVENT_D IS 'event表';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.alarm_id IS '告警ID';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.alarm_type IS '告警类型';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.source_type IS '来源类型';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.monitor_id IS '监测对象ID';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.shaft_floor_id IS '楼层ID';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.partition_code IS '分区编码';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.partition_name IS '分区名称';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.data_reference IS 'MQ数据引用';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.device_token IS '设备编码片段';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.partition_no IS '分区序号';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.source_format IS '数据来源格式';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.event_type IS '事件类型码 0触发1合并2确认3观察4误报5恢复6关闭';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.event_time IS '事件时间';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.event_no IS '事件序号';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.event_level IS '事件等级';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.point_list_json IS '触发点位列表';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.detail_json IS '事件详情';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.content IS '事件内容';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.merged_flag IS '是否合并';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.created_on IS '创建时间';
COMMENT ON COLUMN ODS_DWEQ_DM_EVENT_D.updated_on IS '更新时间';

-- ODS_DWEQ_DM_RAW_DATA_D
COMMENT ON TABLE ODS_DWEQ_DM_RAW_DATA_D IS 'ODS_DWEQ_DM_RAW_DATA_D表';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.iot_code IS '设备唯一标识，取topic设备段';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.topic IS '原始topic';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.partition_id IS '分区标识';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.monitor_id IS '监测对象ID';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.shaft_floor_id IS '楼层ID';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.data_reference IS 'MQ数据引用';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.ied_full_path IS '完整路径';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.collect_time IS '采集时间';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.max_temp IS '最大温度';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.min_temp IS '最小温度';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.avg_temp IS '平均温度';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.max_temp_position IS '最大温度所在位置';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.min_temp_position IS '最小温度所在位置';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.max_temp_channel IS '最大温度所在通道';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.min_temp_channel IS '最小温度所在通道';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.payload_json IS '原始消息项JSON';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_RAW_DATA_D.created_on IS '创建时间';

-- ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D
COMMENT ON TABLE ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D IS 'ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D表';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D.id IS '主键ID';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D.device_id IS '终端ID';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D.status IS '状态';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D.change_time IS '状态变化时间';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D.reason IS '变化原因';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D.deleted IS '是否删除';
COMMENT ON COLUMN ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D.created_on IS '创建时间';


/* =========================================================
   2) 索引补充
   ========================================================= */

-- ODS_DWEQ_DM_DEVICE_D
CREATE INDEX idx_device_iot_code ON ODS_DWEQ_DM_DEVICE_D (iot_code);
CREATE INDEX idx_device_area_deleted ON ODS_DWEQ_DM_DEVICE_D (area_id, deleted);
CREATE INDEX idx_device_org_deleted ON ODS_DWEQ_DM_DEVICE_D (org_id, deleted);

-- ODS_DWEQ_DM_MONITOR_D
CREATE INDEX idx_monitor_area_deleted ON ODS_DWEQ_DM_MONITOR_D (area_id, deleted);

-- ODS_DWEQ_DM_SHAFT_FLOOR_D
CREATE INDEX idx_ODS_DWEQ_DM_SHAFT_FLOOR_D_monitor_deleted ON ODS_DWEQ_DM_SHAFT_FLOOR_D (monitor_id, deleted);
CREATE INDEX idx_ODS_DWEQ_DM_SHAFT_FLOOR_D_device_deleted ON ODS_DWEQ_DM_SHAFT_FLOOR_D (device_id, deleted);

-- ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D
CREATE INDEX idx_ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D_monitor_device_deleted ON ODS_DWEQ_DM_MONITOR_DEVICE_BIND_D (monitor_id, device_id, deleted);

-- ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D
CREATE UNIQUE INDEX uk_ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D_device_partition_deleted
ON ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D (device_id, partition_id, deleted);
CREATE INDEX idx_ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D_partition_deleted
ON ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D (partition_code, deleted);
CREATE INDEX idx_ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D_reference_deleted
ON ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D (data_reference, deleted);
CREATE INDEX idx_ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D_monitor_deleted
ON ODS_DWEQ_DM_MONITOR_PARTITION_BIND_D (monitor_id, deleted);

-- ODS_DWEQ_DM_ALARM_D
CREATE UNIQUE INDEX uk_alarm_merge_key ON ODS_DWEQ_DM_ALARM_D (merge_key);
CREATE INDEX idx_alarm_monitor_type_status_deleted ON ODS_DWEQ_DM_ALARM_D (monitor_id, alarm_type, status, deleted);
CREATE INDEX idx_alarm_device_time ON ODS_DWEQ_DM_ALARM_D (device_id, last_alarm_time);

-- ODS_DWEQ_DM_ALARM_RAW_D
CREATE INDEX idx_ODS_DWEQ_DM_ALARM_RAW_D_iot_time ON ODS_DWEQ_DM_ALARM_RAW_D (iot_code, collect_time);
CREATE INDEX idx_ODS_DWEQ_DM_ALARM_RAW_D_partition_time ON ODS_DWEQ_DM_ALARM_RAW_D (partition_id, collect_time);

-- ODS_DWEQ_DM_ALARM_RULE_D
CREATE INDEX idx_ODS_DWEQ_DM_ALARM_RULE_D_scope
ON ODS_DWEQ_DM_ALARM_RULE_D (biz_type, alarm_type, scope_type, scope_id, enabled, deleted);

-- ODS_DWEQ_DM_EVENT_D
CREATE INDEX idx_event_alarm_time ON ODS_DWEQ_DM_EVENT_D (alarm_id, event_time);
CREATE INDEX idx_event_monitor_time ON ODS_DWEQ_DM_EVENT_D (monitor_id, event_time);

-- ODS_DWEQ_DM_RAW_DATA_D
CREATE INDEX idx_ODS_DWEQ_DM_RAW_DATA_D_iot_time ON ODS_DWEQ_DM_RAW_DATA_D (iot_code, collect_time);
CREATE INDEX idx_ODS_DWEQ_DM_RAW_DATA_D_device_partition_time ON ODS_DWEQ_DM_RAW_DATA_D (device_id, partition_id, collect_time);
CREATE INDEX idx_ODS_DWEQ_DM_RAW_DATA_D_monitor_time ON ODS_DWEQ_DM_RAW_DATA_D (monitor_id, collect_time);
CREATE INDEX idx_ODS_DWEQ_DM_RAW_DATA_D_partition_time ON ODS_DWEQ_DM_RAW_DATA_D (partition_id, collect_time);

-- ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D
CREATE INDEX idx_ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D_device_time ON ODS_DWEQ_DM_DEVICE_ONLINE_LOG_D (device_id, change_time);
